version: "2"
services:
  jackett:
    image: "linuxserver/jackett:${TAG}"
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /usr/local/bin/media/jackett/config:/config
      - /usr/local/bin/media/torrents/downloading:/downloads
    ports:
      - 9117:9117
    restart: always

  transmission:
    image: "linuxserver/transmission:${TAG}"
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /usr/local/bin/media/transmission/config:/config
      - /usr/local/bin/media/torrents/downloading:/downloads
      - /usr/local/bin/media/torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always

  sonarr:
    image: "linuxserver/sonarr:${TAG}"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /usr/local/bin/media/sonarr/config:/config
      - ${TV_PATH}:/tv
      - /usr/local/bin/media/torrents/downloading:/downloads
      - /usr/local/bin/media/torrents/watch:/watch
    depends_on:
      - transmission
      - jackett
    ports:
      - 8989:8989
    restart: always
    
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ${TV_PATH}:/tv
    restart: always
