version: "2"
services:
  jackett:
    image: "linuxserver/jackett:arm32v7-latest"
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /usr/local/bin/rpi-media-as-code/jackett/config:/config
      - /usr/local/bin/rpi-media-as-code/torrents/downloading:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  transmission:
    image: "linuxserver/transmission:arm32v7-latest"
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /usr/local/bin/rpi-media-as-code/transmission/config:/config
      - /usr/local/bin/rpi-media-as-code/torrents/downloading:/downloads
      - /usr/local/bin/rpi-media-as-code/torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  sonarr:
    image: "linuxserver/sonarr:arm32v7-latest"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /usr/local/bin/rpi-media-as-code/sonarr/config:/config
      - /media/nas/anime:/tv
      - /usr/local/bin/rpi-media-as-code/torrents/downloading:/downloads
      - /usr/local/bin/rpi-media-as-code/torrents/watch:/watch
    depends_on:
      - transmission
      - jackett
    ports:
      - 8989:8989
    restart: unless-stopped
