version: "2"
services:
  plex:
    image: "linuxserver/plex:${TAG}"
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /usr/local/bin/rpi-media-as-code/plex/config:/config
      - /media/nas/video/anime:/tvshows
      - /media/nas/video/movies:/movies
      - /media/nas/video/transcoding:/transcode
    restart: unless-stopped

  jackett:
    image: "linuxserver/jackett:${TAG}"
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /usr/local/bin/rpi-media-as-code/jackett/config:/config
      - /media/nas/video/torrents/downloading:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  transmission:
    image: "linuxserver/transmission:${TAG}"
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /usr/local/bin/rpi-media-as-code/transmission/config:/config
      - /media/nas/video/torrents/downloading:/downloads
      - /media/nas/video/torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  sonarr:
    image: "linuxserver/sonarr:${TAG}"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /usr/local/bin/rpi-media-as-code/sonarr/config:/config
      - /media/nas/video/anime:/tv
      - /media/nas/video/torrents/downloading:/downloads
      - /media/nas/video/torrents/watch:/watch
    depends_on:
      - transmission
      - jackett
    ports:
      - 8989:8989
    restart: unless-stopped
